### ISSUE TITLE
server encoding issue

### ISSUE THREAD

**Issue by strongliang** [creadr/creadr-api#7] opened 2017-02-03 17:16 UTC
## input
`http://creadr.io:8081/pinyin/%E7%BB%93%E5%B7%B4`

## error log
```
209.49.4.114 - - [03/Feb/2017 17:14:22] "GET /pinyin/%E7%BB%93%E5%B7%B4 HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/home/strong/.venv/creadr/lib/python2.7/site-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/home/strong/.venv/creadr/lib/python2.7/site-packages/werkzeug/serving.py", line 196, in execute
    write(data)
  File "/home/strong/.venv/creadr/lib/python2.7/site-packages/werkzeug/serving.py", line 161, in write
    self.send_response(int(code), msg)
  File "/home/strong/.venv/creadr/lib/python2.7/site-packages/werkzeug/serving.py", line 272, in send_response
    self.wfile.write(hdr.encode('ascii'))
IOError: [Errno 32] Broken pipe
```

**Comment by MMMartt** [comment] 2017-02-03 21:40
I think this is a duplicate of [pallets/werkzeug#954](https://github.com/pallets/werkzeug/issues/954) instead of an encoding issue. And it shouldn't terminate the program in a production WSGI server.

**Comment by MMMartt** [comment] 2017-02-03 21:46
And discussion [here](http://stackoverflow.com/questions/14207708/ioerror-errno-32-broken-pipe-python) about broken pipe error is pretty good, as I think)

**Comment by strongliang** [comment] 2017-02-05 02:48
interesting read. I'll see if I can reproduce it consistently

**Closed as completed** 2017-02-14 07:05 UTC
Labels: bug
